### ISSUE TITLE
tax being calculated incorrectly...

### ISSUE THREAD

**Issue by proseLA** [lat9/sales_report#19]
https://github.com/lat9/sales_report/blob/5760af5e2ae5be07e3755d20656b5a6cb1f4a933/YOUR_ADMIN/includes/classes/sales_report.php#L385-L386

hi cindy,
i would do a PR but i currently do not have this repo and i'm a little short on time.  if you want me to do it, i will.

i believe the above bit of code is wrong.  i think it should be:

```php
            if (DISPLAY_PRICE_WITH_TAX_ADMIN == 'false') {
                $product_price_inc_tax = zen_round($final_price * $quantity, $currencies->currencies[DEFAULT_CURRENCY]['decimal_places']) + zen_calculate_tax($final_price * $quantity, $tax) + zen_calculate_tax($onetime_charges, $tax);
            } else {
                $product_price_inc_tax = (zen_add_tax($final_price, $tax) * $quantity) + zen_add_tax($onetime_charges,
                        $tax);
            }
```
i'm not 100% on this.  but on my clients sites, sales were showing sales with the tax taxed out twice.  both config keys:  
```
DISPLAY_PRICE_WITH_TAX_ADMIN
DISPLAY_PRICE_WITH_TAX
```

are set to false.

best.

**Comment by lat9** [comment]
Thanks, @proseLA, you're in the right area, but it's the `$product_price_ex_tax` value that's not getting set correctly.  When a store displays prices with tax, the `$product_price_inc_tax` gets set (via that call to `zen_add_tax`) to include the 'added tax'.  The tax, in that case, needs to be backed out for the _ex tax_ display:
```
                // Calculate the subtotal inc tax in the same way that the order class does
                $product_price_inc_tax = (zen_add_tax($final_price, $tax) * $quantity) + zen_add_tax($onetime_charges, $tax);
                $product_price_exc_tax = (DISPLAY_PRICE_WITH_TAX_ADMIN == 'true') ? ($product_price_inc_tax - $product_tax) : $product_price_inc_tax;
```
