### ISSUE TITLE
zc156 interoperability: Custom date field displays "off-page".

### ISSUE THREAD

**Issue by lat9** [lat9/sales_report#5]
As [reported ](https://www.zen-cart.com/showthread.php?44669-Sales-report-2-0&p=1355708#post1355708)in the plugin's Zen Cart support-thread, when you choose a "Custom" date range, the spiffyCal calendar's display is "off-page":
![image](https://user-images.githubusercontent.com/2685585/54049478-987bb280-41aa-11e9-8876-b660364a9e61.png)

**Comment by proseLA** [comment]
cindy,
i have done some work on this issue.  i have removed the spiffycal and used the datePicker already inherent in the jQuery ui that is now part of the base.  if you want me to post any of the code, let me know.
best.
